<fieldset class="fieldset create account">
    <div class="field mobile">
        <label for="nickname" class="label"><span><?php echo __('Your Secret Nickname') ?></span></label>
        <div class="control">
            <input type="text"
                   name="nickname"
                   id="nickname"
                   class="input-text"
                   autocomplete="off">
            <span><?php echo __('Example:(__AMG__)') ?></span>
        </div>
    </div>
</fieldset>