
<fieldset class="fieldset edit account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field mobile required">

        <label for="telephone" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Phone Number') ?></span></label>

        <div class="control">
            <input type="text"
                   name="telephone"
                   id="telephone"
                   value="<?php echo $block->getCustomer()->getCustomAttribute('telephone')->getValue() ?>"
                   title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>"
                   class="input-text"
                   data-validate="{required:true}"
                   autocomplete="off">
        </div>
    </div>
</fieldset>