<?php

namespace Learn\BigBoats\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;;

class SayHello extends Command
{
    const NAME = 'name';

    protected function configure()
    {
        $this->setName('learn:hello:magento')
            ->setDescription('the command prints out hello')
            ->setAliases(array('sh'));

        $this->addOption(
            self::NAME,
            null,
            InputOption::VALUE_REQUIRED,
            'Name'
        );

        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if ($name = $input->getOption(self::NAME)) {
            $output->writeln('<info>Hello `' . $name . '`</info>');
        }

        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
